/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_session_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_session_post"];
        /** Delete Session */
        delete: operations["delete_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employee Profile */
        get: operations["employee_profile_api_employee_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Employee Recommendations */
        post: operations["employee_recommendations_api_employee_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/events/{event_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Event */
        post: operations["complete_event_api_employee_events__event_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/events/{event_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Event */
        post: operations["dismiss_event_api_employee_events__event_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_hr_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_hr_dataset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Runs */
        get: operations["agent_runs_api_hr_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityStatus: "completed" | "in_progress" | "dropped" | "no_show" | "declined" | "overdue";
        /** AgentRunListOut */
        AgentRunListOut: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["AgentRunOut"][];
        };
        /** AgentRunOut */
        AgentRunOut: {
            /** Id */
            id: number;
            /** Employee Id */
            employee_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "recommendation" | "debug";
            /** User Input */
            user_input: string;
            /** Answer */
            answer: string;
            /** Steps */
            steps: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latency Ms */
            latency_ms: number | null;
            /** Fallback Used */
            fallback_used: boolean;
        };
        /** AgentStep */
        AgentStep: {
            /** Tool */
            tool: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_dataset_api_hr_dataset_post */
        Body_upload_dataset_api_hr_dataset_post: {
            /** Employees */
            employees: string;
            /** Events */
            events: string;
            /** Skills */
            skills: string;
            /** Activity History */
            activity_history: string;
        };
        /** Candidate */
        Candidate: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            format: components["schemas"]["EventFormat"];
            /** Duration Hours */
            duration_hours: number;
            /** Next Session */
            next_session: string | null;
            factors: components["schemas"]["RecommendationFactors"];
            history: components["schemas"]["HistoryEvidence"];
            /** Changes */
            changes: components["schemas"]["SkillChange"][];
            /** Readiness Before */
            readiness_before: number | null;
            /** Readiness After */
            readiness_after: number | null;
            /** Critical Skills Closed */
            critical_skills_closed: string[];
            /** Score */
            readonly score: number;
        };
        /** CompletionOut */
        CompletionOut: {
            /** Record Id */
            record_id: string;
            /** Event Id */
            event_id: string;
            progress: components["schemas"]["ProgressOut"];
        };
        /** DatasetCountsOut */
        DatasetCountsOut: {
            /** Metadata */
            metadata: number;
            /** Employees */
            employees: number;
            /** Employee Skills */
            employee_skills: number;
            /** Skills */
            skills: number;
            /** Role Profiles */
            role_profiles: number;
            /** Grade Requirements */
            grade_requirements: number;
            /** Events */
            events: number;
            /** Event Skills */
            event_skills: number;
            /** Activity History */
            activity_history: number;
        };
        /** DatasetUploadOut */
        DatasetUploadOut: {
            /**
             * Status
             * @constant
             */
            status: "loaded";
            /** Dataset */
            dataset: string;
            /** Version */
            version: string;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            counts: components["schemas"]["DatasetCountsOut"];
        };
        /** DepartmentOverview */
        DepartmentOverview: {
            /** Department */
            department: string;
            /** Employee Count */
            employee_count: number;
            /** Employees With Trajectory */
            employees_with_trajectory: number;
            /** Average Readiness */
            average_readiness?: number | null;
        };
        /** DismissOut */
        DismissOut: {
            /** Event Id */
            event_id: string;
            /**
             * Status
             * @constant
             */
            status: "dismissed";
        };
        /** EmployeeListItem */
        EmployeeListItem: {
            /** Employee Id */
            employee_id: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Grade */
            grade: string;
        };
        /** EmployeeProfileOut */
        EmployeeProfileOut: {
            /** Employee Id */
            employee_id: string;
            /** Full Name */
            full_name: string;
            /** Department */
            department: string;
            /** Role */
            role: string;
            /** Grade */
            grade: string;
            /** Tenure Months */
            tenure_months: number;
            /** Work Format */
            work_format: string;
            /** Preferred Language */
            preferred_language: string;
            /** Career Goal */
            career_goal: {
                [key: string]: string;
            } | null;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Skills */
            skills: components["schemas"]["SkillOut"][];
            trajectory: components["schemas"]["Trajectory"];
            /** History */
            history: components["schemas"]["HistoryOut"][];
        };
        /** @enum {string} */
        EventFormat: "online" | "offline" | "self_paced";
        /** FactorExplanation */
        FactorExplanation: {
            factor: components["schemas"]["FactorName"];
            /** Value */
            value: number;
            /** Explanation */
            explanation: string;
        };
        /** @enum {string} */
        FactorName: "gap_closure" | "grade_relevance" | "history_affinity" | "format_fit";
        /** @enum {string} */
        FallbackReason: "timeout" | "round_limit" | "invalid_response" | "openai_error";
        /** @enum {string} */
        Grade: "Junior" | "Middle" | "Senior" | "Lead";
        /** HROverviewOut */
        HROverviewOut: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Employee Count */
            employee_count: number;
            /** Department Count */
            department_count: number;
            /** Employees With Trajectory */
            employees_with_trajectory: number;
            /** Promotion Ready Count */
            promotion_ready_count: number;
            /** Average Readiness */
            average_readiness?: number | null;
            /** Departments */
            departments: components["schemas"]["DepartmentOverview"][];
            /** Skill Gaps */
            skill_gaps: components["schemas"]["SkillGapOverview"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** HistoryEvidence */
        HistoryEvidence: {
            /** Completed */
            completed: number;
            /** Unsuccessful */
            unsuccessful: number;
            /** Record Ids */
            record_ids: string[];
            /** Affinity */
            readonly affinity: number;
        };
        /** HistoryOut */
        HistoryOut: {
            /** Record Id */
            record_id: string;
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            status: components["schemas"]["ActivityStatus"];
            /** Completion Pct */
            completion_pct: number;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Readiness Before */
            readiness_before: number | null;
            /** Readiness After */
            readiness_after: number | null;
            /** Changes */
            changes: components["schemas"]["SkillChange"][];
        };
        /** Recommendation */
        Recommendation: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /** Explanation */
            explanation: string;
            /** Factors */
            factors: components["schemas"]["FactorExplanation"][];
            facts: components["schemas"]["Candidate"];
        };
        /** RecommendationFactors */
        RecommendationFactors: {
            /** Gap Closure */
            gap_closure: number;
            /** Grade Relevance */
            grade_relevance: number;
            /** History Affinity */
            history_affinity: number;
            /** Format Fit */
            format_fit: number;
            /** Score */
            readonly score: number;
        };
        /** RecommendationIn */
        RecommendationIn: {
            /**
             * Message
             * @default Подбери следующие шаги развития
             */
            message: string;
        };
        /** RecommendationRun */
        RecommendationRun: {
            /** Answer */
            answer: string;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "no_candidates";
            /** Fallback Used */
            fallback_used: boolean;
            fallback_reason: components["schemas"]["FallbackReason"] | null;
            /** Steps */
            steps: components["schemas"]["AgentStep"][];
            /** Latency Ms */
            latency_ms: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** @enum {string} */
        Role: "employee" | "hr";
        /** SessionIn */
        SessionIn: {
            role: components["schemas"]["Role"];
            /** Employee Id */
            employee_id?: string | null;
        };
        /** SessionOut */
        SessionOut: {
            role: components["schemas"]["Role"];
            /** Employee Id */
            employee_id: string | null;
        };
        /** SkillChange */
        SkillChange: {
            /** Skill Id */
            skill_id: string;
            before: components["schemas"]["SkillLevel"];
            after: components["schemas"]["SkillLevel"];
            /** Gain */
            readonly gain: number;
        };
        /** SkillGap */
        SkillGap: {
            /** Skill Id */
            skill_id: string;
            current: components["schemas"]["SkillLevel"];
            required: components["schemas"]["SkillLevel"];
            gap: components["schemas"]["SkillLevel"];
            /** Is Critical */
            is_critical: boolean;
        };
        /** SkillGapOverview */
        SkillGapOverview: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Employees With Gap */
            employees_with_gap: number;
            /** Average Gap */
            average_gap: number;
        };
        SkillLevel: number;
        /** SkillOut */
        SkillOut: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Level */
            level: number;
        };
        /** Trajectory */
        Trajectory: {
            /** Employee Id */
            employee_id: string;
            /** Role */
            role: string;
            current_grade: components["schemas"]["Grade"];
            target_grade: components["schemas"]["Grade"] | null;
            /** Readiness */
            readiness: number | null;
            /** Critical Skills Met */
            critical_skills_met: boolean | null;
            /** Skills */
            skills: components["schemas"]["SkillGap"][];
            /** Gaps */
            readonly gaps: components["schemas"]["SkillGap"][];
            /** Promotion Ready */
            readonly promotion_ready: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    create_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_employees_api_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeListItem"][];
                };
            };
        };
    };
    employee_profile_api_employee_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeProfileOut"];
                };
            };
        };
    };
    employee_recommendations_api_employee_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_event_api_employee_events__event_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_event_api_employee_events__event_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_hr_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HROverviewOut"];
                };
            };
        };
    };
    upload_dataset_api_hr_dataset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_hr_dataset_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_runs_api_hr_agent_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
