"""add career quest schema

Revision ID: eab2d772e58c
Revises: 10eccd36a138
Create Date: 2026-09-23 15:23:33.975772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eab2d772e58c"
down_revision: str | Sequence[str] | None = "10eccd36a138"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_metadata",
        sa.Column("source_filename", sa.Text(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column(
            "proficiency_scale",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("source_filename"),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("target_roles", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("target_grades", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "prerequisites", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("upcoming_sessions", postgresql.ARRAY(sa.Date()), nullable=False),
        sa.CheckConstraint(
            "format IN ('online', 'offline', 'self_paced')", name="ck_events_format"
        ),
        sa.CheckConstraint(
            "type IN ('compliance', 'onboarding', 'course', 'workshop', 'mentoring', 'certification', 'meetup')",
            name="ck_events_type",
        ),
        sa.CheckConstraint("duration_hours > 0", name="ck_events_duration_hours"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "role_profiles",
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("grade", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "grade IN ('Junior', 'Middle', 'Senior', 'Lead')",
            name="ck_role_profiles_grade",
        ),
        sa.PrimaryKeyConstraint("role", "grade"),
    )
    op.create_table(
        "skills",
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint("type IN ('hard', 'soft')", name="ck_skills_type"),
        sa.PrimaryKeyConstraint("skill_id"),
    )
    op.create_table(
        "employees",
        sa.Column("employee_id", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("department", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("grade", sa.Text(), nullable=False),
        sa.Column("manager_id", sa.Text(), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("tenure_months", sa.Integer(), nullable=False),
        sa.Column("work_format", sa.Text(), nullable=False),
        sa.Column("preferred_language", sa.Text(), nullable=False),
        sa.Column(
            "career_goal",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("last_review_date", sa.Date(), nullable=False),
        sa.CheckConstraint(
            "preferred_language IN ('kk', 'ru', 'en')",
            name="ck_employees_preferred_language",
        ),
        sa.CheckConstraint(
            "work_format IN ('office', 'hybrid', 'remote')",
            name="ck_employees_work_format",
        ),
        sa.CheckConstraint(
            "last_review_date >= hire_date", name="ck_employees_review_after_hire"
        ),
        sa.CheckConstraint(
            "manager_id <> employee_id", name="ck_employees_manager_not_self"
        ),
        sa.CheckConstraint("tenure_months >= 0", name="ck_employees_tenure_months"),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.employee_id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["role", "grade"],
            ["role_profiles.role", "role_profiles.grade"],
            name="fk_employees_role_profile",
        ),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "event_skills",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("gain", sa.SmallInteger(), nullable=False),
        sa.Column("max_level", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("gain > 0", name="ck_event_skills_gain"),
        sa.CheckConstraint(
            "max_level BETWEEN 0 AND 5", name="ck_event_skills_max_level"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.skill_id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "skill_id"),
    )
    op.create_table(
        "grade_requirements",
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("grade", sa.Text(), nullable=False),
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("required_level", sa.SmallInteger(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "required_level BETWEEN 0 AND 5", name="ck_grade_requirements_level"
        ),
        sa.ForeignKeyConstraint(
            ["role", "grade"],
            ["role_profiles.role", "role_profiles.grade"],
            name="fk_grade_requirements_role_profile",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.skill_id"],
        ),
        sa.PrimaryKeyConstraint("role", "grade", "skill_id"),
    )
    op.create_table(
        "activity_history",
        sa.Column("record_id", sa.Text(), nullable=False),
        sa.Column("employee_id", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("completion_pct", sa.SmallInteger(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("feedback_rating", sa.SmallInteger(), nullable=True),
        sa.Column("assigned_by", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "assigned_by IN ('self', 'manager', 'hr')",
            name="ck_activity_history_assigned_by",
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'in_progress', 'dropped', 'no_show', 'declined', 'overdue')",
            name="ck_activity_history_status",
        ),
        sa.CheckConstraint(
            "completion_pct BETWEEN 0 AND 100",
            name="ck_activity_history_completion_pct",
        ),
        sa.CheckConstraint(
            "feedback_rating BETWEEN 1 AND 5",
            name="ck_activity_history_feedback_rating",
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_activity_history_score"),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.employee_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        "ix_activity_history_employee_date",
        "activity_history",
        ["employee_id", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_history_event_id"),
        "activity_history",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "dismissals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.employee_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dismissals_employee_event",
        "dismissals",
        ["employee_id", "event_id"],
        unique=False,
    )
    op.create_table(
        "employee_skills",
        sa.Column("employee_id", sa.Text(), nullable=False),
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("level BETWEEN 0 AND 5", name="ck_employee_skills_level"),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.employee_id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.skill_id"],
        ),
        sa.PrimaryKeyConstraint("employee_id", "skill_id"),
    )
    op.add_column("agent_runs", sa.Column("employee_id", sa.Text(), nullable=True))
    op.add_column(
        "agent_runs",
        sa.Column("kind", sa.Text(), server_default="debug", nullable=False),
    )
    op.add_column("agent_runs", sa.Column("latency_ms", sa.Integer(), nullable=True))
    op.add_column(
        "agent_runs",
        sa.Column(
            "fallback_used",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # Alembic does not autogenerate added CHECK constraints on existing tables.
    op.create_check_constraint(
        "ck_agent_runs_kind", "agent_runs", "kind IN ('recommendation', 'debug')"
    )
    op.create_check_constraint(
        "ck_agent_runs_latency_ms", "agent_runs", "latency_ms >= 0"
    )
    op.create_index(
        "ix_agent_runs_employee_created_at",
        "agent_runs",
        ["employee_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_agent_runs_employee_id",
        "agent_runs",
        "employees",
        ["employee_id"],
        ["employee_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_agent_runs_employee_id", "agent_runs", type_="foreignkey")
    op.drop_index("ix_agent_runs_employee_created_at", table_name="agent_runs")
    op.drop_constraint("ck_agent_runs_latency_ms", "agent_runs", type_="check")
    op.drop_constraint("ck_agent_runs_kind", "agent_runs", type_="check")
    op.drop_column("agent_runs", "fallback_used")
    op.drop_column("agent_runs", "latency_ms")
    op.drop_column("agent_runs", "kind")
    op.drop_column("agent_runs", "employee_id")
    op.drop_table("employee_skills")
    op.drop_index("ix_dismissals_employee_event", table_name="dismissals")
    op.drop_table("dismissals")
    op.drop_index(op.f("ix_activity_history_event_id"), table_name="activity_history")
    op.drop_index("ix_activity_history_employee_date", table_name="activity_history")
    op.drop_table("activity_history")
    op.drop_table("grade_requirements")
    op.drop_table("event_skills")
    op.drop_table("employees")
    op.drop_table("skills")
    op.drop_table("role_profiles")
    op.drop_table("events")
    op.drop_table("dataset_metadata")
    # ### end Alembic commands ###
